### ISSUE TITLE
Widgets - Footer

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#12]

**Comment by Ethan-Flynn** [comment]
- The blue for the links needs to be #4178da. 
- Need 50 px between each link at the bottom of the footer. Also need to ensure these links are left justified (Terms and Conditions flushed with the left copy in paragraph above)

**Comment by diggs00** [comment]
@Ethan-Flynn

Did you all change the link color?
The original blue link color was: #1864ec;

**Comment by Ethan-Flynn** [comment]
As mentioned in the Finance Widget, I am going to keep this open until I can verify with our creative team.
