### ISSUE TITLE
Widgets - Finance

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#14]

**Comment by Ethan-Flynn** [comment]
Need to make the 'X' and 'Remove' #4178da. This color should also be used for the Manage GM Card CTA.

**Comment by diggs00** [comment]
@Ethan-Flynn 

Did you all change the link color?
The original blue link color was: #1864ec;

**Comment by Ethan-Flynn** [comment]
I am going to leave this open until I can confirm with our creative team that this color, along with a few others, has officially changed. I owe you an updated pattern library reflecting recent color updates. We are set to meet internally for a final time on Wednesday to finish our internal review of the pattern library. At that time I will have the creative team update the pattern library and provide you with the most up-to-date version to date.
