### ISSUE TITLE
Widgets - Garage

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#16]

**Comment by Ethan-Flynn** [comment]
Need to remove the OnStar logo from the first expand/collapse box. 

Need 20px of space between View Vehicle Profile and Learn About This Vehicle buttons.

**Comment by diggs00** [comment]
@Ethan-Flynn 

"Need 20px of space between View Vehicle Profile and Learn About This Vehicle buttons."

All buttons will now have 20px inbetween when stacked, you ok with this?

**Comment by Ethan-Flynn** [comment]
Yes. I am okay with that. Thanks!
