### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#27]

**Comment by Ethan-Flynn** [comment]
Desktop table should have #454545 category titles.

**Comment by Ethan-Flynn** [comment]
Add padding between columns in mobile tables. Please see style guide for details.

**Comment by diggs00** [comment]
Tables will be revisited after 4/10 launch

**Comment by Ethan-Flynn** [comment]
Sounds good.. Thanks!
