### ISSUE TITLE
Expand Collapse

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#31]

**Comment by Ethan-Flynn** [comment]
Hey David -

The background color of the Expand/Collapse boxes should be white when expanded. The title box remains white at all times, expanded box background should also be white.

**Comment by Ethan-Flynn** [comment]
Please use correct green check icon.

**Comment by diggs00** [comment]
Ethan,

I need all icons updated to reflect new style. 
OC's current icons :+1: http://diggs00.github.io/GMOC-styleguide/index.html?p=icons

**Comment by Ethan-Flynn** [comment]
Hey David - We will revisit the icons once we complete the iconongraphy work that I am working on with the creative team. For the time being please use current OC icons. Thanks
