### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#33]

**Comment by Ethan-Flynn** [comment]
Pill tabs should be white when active.

**Comment by Ethan-Flynn** [comment]
Button tabs need to be butted up against the content area. Content area should be white.

**Comment by diggs00** [comment]
Tabs will be revisited after 4/10 launch

**Comment by Ethan-Flynn** [comment]
Okay. Sounds good. Thanks
