### ISSUE TITLE
Password Strength Meter

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#43]

**Comment by Ethan-Flynn** [comment]
Form field box should be red when in an error state.

**Comment by Ethan-Flynn** [comment]
Text beneath field should show status with color as well.

**Comment by diggs00** [comment]
@Ethan-Flynn 
1. Form field box should be red when in an error state.
Will be done in production
2.Text beneath field should show status with color as well.
Will be done in production

**Comment by Ethan-Flynn** [comment]
By stating these updates will be done in production, that is saying that what we (MRM) asked for will be completed, correct?

**Comment by diggs00** [comment]
Yes, different code for production than style guide for meter. Your request will happen.

**Comment by diggs00** [comment]
Yes, different code for production than style guide for meter. Your request will happen.
