### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#44]

**Comment by Ethan-Flynn** [comment]
Small paragraph text should be #acacac.

**Comment by Ethan-Flynn** [comment]
The Chevy H1 should be Louis Bold Italic.

**Comment by Ethan-Flynn** [comment]
All H1’s (which are 45/50px in desktop viewports) will become 35/40px in mobile viewports. Please update. Thanks!

**Comment by diggs00** [comment]
@Ethan-Flynn 
1. Small paragraph text should be #acacac: CORRECTED
2. The Chevy H1 should be Louis Bold Italic. CORRECTED
3. All H1’s will become 35/40px in mobile viewports. ADDED

**Comment by Ethan-Flynn** [comment]
Hey David - I do not see a question attache to this section? Is there an outstanding question regarding the updates I submitted for this section? Thanks!

**Comment by diggs00** [comment]
@Ethan-Flynn  just need your approval please

**Comment by Ethan-Flynn** [comment]
This is approved. Thanks
