### ISSUE TITLE
Widgets : Footer

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#45]

**Comment by Ethan-Flynn** [comment]
Footer links should not be underlined. The main text area should be styled as a disclaimer.

**Comment by diggs00** [comment]
@Ethan-Flynn 
1.Footer links should not be underlined. CORRECTED
2. The main text area should be styled as a disclaimer. NOT CORRECTED it is already using the small ext (disclaimer)

**Comment by Ethan-Flynn** [comment]
This is correct. Nothing needs to be corrected. Thanks
