### ISSUE TITLE
Widgets : Card-Default

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#46]

**Comment by Ethan-Flynn** [comment]
Title H4 should include an icon.

**Comment by diggs00** [comment]
@Ethan-Flynn 

There is No icon within the card. NO CHANGE NEEDED

**Comment by Ethan-Flynn** [comment]
This is fine for the April launch. In the future when the icon library has been finalized, we will need to be incorporate this into the header area.

**Comment by diggs00** [comment]
Yes
