### ISSUE TITLE
Widgets : Card-Brand

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#47]

**Comment by Ethan-Flynn** [comment]
H4 should be in all caps in the brand font.

**Comment by Ethan-Flynn** [comment]
BYO image should be included in background.

**Comment by diggs00** [comment]
@Ethan-Flynn 
1. H4 should be in all caps in the brand font. CORRECTED
2. BYO????

**Comment by Ethan-Flynn** [comment]
Hey David - BYO refers to the Build Your Own feature. This image should be provided by the service that provides the other card images. If need be, we can hop on a quick call about this one. Please let me know.. Thanks!
