### ISSUE TITLE
Widgets : Card-Tertiary

### ISSUE THREAD

**Issue by diggs00** [diggs00/GMOC-styleguide#49]

**Comment by Ethan-Flynn** [comment]
Card background should be white.

**Comment by Ethan-Flynn** [comment]
Rule beneath card header should be secondary blue.

**Comment by Ethan-Flynn** [comment]
Card header should be paired with icon.

**Comment by diggs00** [comment]
@Ethan-Flynn 

FYI: Your Tertiary representation is our Default representation.

**Comment by Ethan-Flynn** [comment]
Please use the tertiary card style as the default card style. Thanks!
